GLOBAL:
  USE_GPU: true
  RESUME: false
  RESUME_PATH: "${BASE_DIR}/train_log/2022-0926_1009/checkpoints/best.pth" # model checkpoint
  DEVICE: 'cpu' # 'cpu' or '0' or '0,1,2,3' ...
  EPOCH_NUM: 2 # how many epochs to train the model for
  SAVE_RESULT_DIR: "${BASE_DIR}/train_log" # where to save the model
  SAVE_EPOCH_STEP: 1 # how frequently save a model
  VAL_EPOCH_STEP: 1 # how frequently perform validation
  LOG_EPOCH_STEP: 1 # how frequently log the model progress, 1 - every step
  DISTRIBUTED: true
  EARLY_STOP_PATIENCE: 5 # how long to wait before observing no gradual changes
  TRAIN_DIR: "${BASE_DIR}/data_dir/train"
  VAL_DIR: "${BASE_DIR}/data_dir/val"
  TEST_DIR: "${BASE_DIR}/data_dir/test"
  USE_AMP: false
  LANG_SRC: "en"
  LANG_TGT: "it"
  SEQ_LEN: 350
  SENTENCE: "this is a test sentence"
  DECODING_STRATEGY: 'beam'
  

TRAIN:
  TRAIN_BATCHSIZE_PER_CARD: 4
  VAL_BATCHSIZE_PER_CARD: 1
  DROP_LAST: true
  NUM_WORKERS: 4

DATASET:
  THRESHOLD: 4

MODEL:
  NAME: transformer
  d_model: 512
  BLOCKS: 6
  HEADS: 8
  DROPOUT: 0.1
  d_ff: 2048
  

CRITERION:
  NAME: CE
  COORD_RATIO: 1
  CLASSIFIER_RATIO: 0.5

OPTIMIZER:
  NAME: Adam
  LEARNING_RATE: 0.01
  BETA1: 0.9
  BETA2: 0.999
  WEIGHT_DECAY: 0
  # LR_NAME: linear_lr
  LR_NAME: none # scheduler
  LR_DECAY: 0.1 # controls the scaling factor of the learning rate